jobs:
  convention_commit_check:
    name: Run conventional commit style check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check the commit style against the 'conventional commit styling'
      uses: MichaelsJP/action-conventional-commits@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALID_LABELS: '["feat","fix","docs","style","refactor","test","build","perf","ci","chore","revert","merge","wip"]'
  conventional_commit_pr_title_check:
    name: Check the PR title against the 'conventional commit styling'
    permissions:
      statuses: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: aslafy-z/conventional-pr-title-action@v3
name: Conventional commit checks
on:
  repository_dispatch:
    types: trigger-ga___conventional-commit.yml
