concurrency:
  cancel-in-progress: false
  group: pages
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache: npm
        node-version: 20
    - continue-on-error: true
      name: Setup Pages
      uses: actions/configure-pages@v3
    - continue-on-error: true
      name: Install dependencies
      run: npm ci
    - continue-on-error: true
      name: Build with VitePress
      run: 'npm run docs:build # or pnpm docs:build / yarn docs:build / bun run docs:build

        touch docs/.vitepress/dist/.nojekyll

        '
    - continue-on-error: true
      name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: docs/.vitepress/dist
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: deployment
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
name: Deploy Backend Documentation to Pages
on:
  repository_dispatch:
    types: trigger-ga___deploy-docs.yml
permissions:
  contents: read
  id-token: write
  pages: write
