jobs:
  Handle_event:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        PROJECT_AUTOMATION: ${{ secrets.PROJECT_AUTOMATION }}
      if: env.PROJECT_AUTOMATION != null
      name: run project board action
      uses: takb/project-board@master
      with:
        columnbylabel: '{":bug: bug": "Priority"}'
        ignorecolumnnames: Priority,Assigned,In progress,Review,Awaiting release,Done
        owner: GIScience
        project: '16'
        repo: openrouteservice
        token: ${{ secrets.PROJECT_AUTOMATION }}
name: project_automation
on:
  repository_dispatch:
    types: trigger-ga___project_automation.yml
