jobs:
  actions-tagger:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: Actions-R-Us/actions-tagger@v2
      with:
        publish_latest_tag: true
name: Sync Semver to major and latest tags
on:
  repository_dispatch:
    types: trigger-ga___release-tag-latest.yml
