jobs:
  run_tests:
    name: Run unit and integration tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-sonar
        path: ~/.sonar/cache
        restore-keys: ${{ runner.os }}-sonar
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Test, build, run API tests
      run: mvn -B verify -Papitests -DCI=true
    - continue-on-error: true
      name: Run tests with pre-built graphs from previous run
      run: mvn -B verify -Papitests jacoco:report
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: env.SONAR_TOKEN != null
      name: run SonarLint checks
      run: mvn -B package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
    - continue-on-error: true
      env:
        ROCKETCHAT_WEBHOOK: ${{ secrets.ROCKETCHAT_WEBHOOK }}
      if: env.ROCKETCHAT_WEBHOOK != null
      name: Rocket.Chat Notification
      uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
      with:
        job_name: '*ORS CI Test*'
        token: ${{ secrets.PROJECT_AUTOMATION }}
        type: ${{ job.status }}
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___run_maven_tests.yml
